name: Pengy
favicon: null
layout_spectrum: 0.9829530245624483
typography_spectrum: 0.2822228216100484
title: 'What we do in life, shall echo in eternity!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.12121623195707798
  lightness: 0.05538571858778596
  saturation: 0.885563321178779
  rhythmicContrast: 0.8365331436507404
purpose: []
